# Use the official Node.js 18 image as the base image
FROM node:18 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and yarn.lock files to the working directory
COPY package.json yarn.lock ./

# Install the dependencies
RUN yarn install

# Expose the port on which the application will listen
EXPOSE 3000

# Start the NestJS application
CMD ["yarn", "start:dev"]
