version: '3.8'
services:
  apy:
    image: thanawatpetchuen/apy-calculator:latest
    ports:
      - 3000:3000
    env_file:
      - path: ./.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
